### ISSUE TITLE
Emit literal numerals in systemverilog

### ISSUE THREAD

**Issue by blaxill** [project-oak/silveroak#238]
Currently when building a constant vector e.g. `VecLit [Gnd, Vcc, Gnd]` the emitted systemverilog outputs the value directly:

```
  assign v1 = '{zero,one,zero};
```

We could instead output a literal: 

```
  assign v1 = 3'h2;
```

**Comment by satnam6502** [comment]
To help with debugging generated SystemVerilog.

**Comment by satnam6502** [comment]
@blaxill please can you confirm you want the literals in hex?
Also, please can you confirm _why_ you want the literals? I think you said for debugging? In that case, is it sufficient to just emit a comment after the assignment which gives the value in binary, decimal and hex?
Thanks.

**Comment by satnam6502** [comment]
I think the new scheme that emits hex is good enough for now.
