### ISSUE TITLE
Cache `build_verilator` step

### ISSUE THREAD

**Issue by blaxill** [project-oak/silveroak#308]
`build_verilator` is now our slowest CI step and it should be cached rather than rebuilt each run anyway.

**Comment by jadephilipoom** [comment]
Once this is done, `make_cava_coq` build step should be removed; the `make_all` step would also build the same files, and the only reason they're prebuilt separately is to make maximum progress while waiting for build_verilator.

**Comment by jadephilipoom** [comment]
Closing this, since I believe after the move to Actions we no longer have this problem.
