### ISSUE TITLE
Extra `Byte0` module identifier in Cava2HDL.cabal

### ISSUE THREAD

**Issue by jadephilipoom** [project-oak/silveroak#358]
Continued from #354 

Why is this line required in `other-modules` for `Cava2HDL.cabal`, and can we get rid of it?
https://github.com/project-oak/oak-hardware/blob/d708157e89b2b7cdf7a30c1ac57fb4cf3ba980ca/cava/Cava2HDL.cabal#L94

**Comment by blaxill** [comment]
This is because we are now using definitions from Coq.Strings.Byte and Coq.Init.Byte in extracted files and they both extract to Byte.hs.

**Comment by satnam6502** [comment]
I suspect this is not anything we can easily change since it is not in our code. Closing.
