### ISSUE TITLE
Rename repo to silveroak and document changes to CI

### ISSUE THREAD

**Issue by satnam6502** [project-oak/silveroak#438]
I tried to rename our repo on GitHib to `silveroak` but failed because it broke CI.
Please can the changes required to CI be documented on our repo somewhere and then please can the repo be renamed.
The old repo name will continue to work but I am keen for us to officially rename to `project-oak/silveroak` in preparation for a tagged release. Thank you.

**Comment by blaxill** [comment]
CI should be working now, leaving this issue open until a few real PRs have gone through (i've tried with draft PRs)
