### ISSUE TITLE
Create scripts to build OpenTitan with SilverOak replacements

### ISSUE THREAD

**Issue by blaxill** [project-oak/silveroak#488]
Currently blocked on #498 #499

- Building with replacements of combinational blocks:
  - [X] - SubBytes
  - [X] - ShiftRows
  - [X] - MixColumns
- Building with aes_cipher_core

Initial step towards #464

**Comment by blaxill** [comment]
OpenTitan notes. After tools are installed:
- `fusesoc --cores-root . run --flag=fileset_top --target=sim --setup --build lowrisc:systems:top_earlgrey_verilator`
- `./meson_init.sh `
- `ninja -C build-out all` (this builds aes_test.c, so re-run if disabling mask)
- `build/lowrisc_systems_top_earlgrey_verilator_0.1/sim-verilator/Vtop_earlgrey_verilator   --meminit=rom,build-bin/sw/device/boot_rom/boot_rom_sim_verilator.elf --meminit=flash,build-bin/sw/device/tests/aes_test_sim_verilator.elf   +UARTDPI_LOG_uart0=-` AES test execution with verilator and UART out redirected to console

**Comment by blaxill** [comment]
This has been completed for the combinational components, with `aes_cipher_core` remaining.

**Comment by jadephilipoom** [comment]
Looking at the discussion in https://github.com/project-oak/silveroak/pull/464, it appears this work was completed; I'm closing the issue.
