### ISSUE TITLE
Audit Candidates for OpenTitan Firmware reimplementation in Silver Oak Phase 2

### ISSUE THREAD

**Issue by satnam6502** [project-oak/silveroak#585]
As we approach phase 2 I think it would be good to audit the C code that forms the firmware of OpenTitan (I think this is the code destined for the mask ROM?). We've talked about doing the AES control code first. I think this task will have the property that we will work say 90% of the time hooking up the appropriate instructure and 10% of the time on the C code, perhaps with steps like:

1. extract just the C/RISC-V code in aes.c, verify properties, substitute and test
2. model register interface in Coq, hopefully prove richer properties?
3. model TileLink interface / bus interface protocol, or maybe stub to start with
4. model the register behaviour of the AES peripheral, proofs etc.

Once that is done (which would be a great accomplishment) we should have a good idea about what other parts of the OpenTitan code base we should tackle next, with a preference with code that is a bit more complicated than the AES control code since the AES control is not a lot of code or very complicated.

**Comment by jadephilipoom** [comment]
This was done a while ago; after the audit we decided to work on the UART block first, and then after further discussions with OpenTitan we decided to work on the HMAC block next (since it's included in the firmware that can't be changed after tapeout). Closing the issue.
