### ISSUE TITLE
FPGA implementation status

### ISSUE THREAD

**Issue by blaxill** [project-oak/silveroak#601]
Combinational blocks
- [x] - Netlist
- [x] - Coq tests
- [x] - OT aes_test.c
- [x] - Vivado Synthesis 
- [ ] - (Optional) Performance regression / performance fixing 

Sequential `aes_cipher_core`
- [x] - Netlist based on OT 
- [x] - Observed correct handshaking signalling 
- [x] - OT aes_test.c
- [ ] - (Optional) Performance regression / performance fixing 

Note SilverOak `aes_cipher_core` does not (currently?) have full OT capabilities and so resource usage is not directly comparable.

**Comment by jadephilipoom** [comment]
I think this was completed in phase 1; closing the issue.
