### ISSUE TITLE
Make a reference page

### ISSUE THREAD

**Issue by jadephilipoom** [project-oak/silveroak#667]
As I've been writing the Cava tutorial, I keep wishing there was a more comprehensive reference I could point people to for further information rather than explaining everything inline. Just one or two sentences about each definition would be enough.

I think such a reference would be generally useful for people figuring out how to write circuits, as well -- just a place where you can see all the library definitions that are available to you for building circuits, with perhaps some other sections explaining e.g. the different monad notations or `Circuit` constructors. That way no one has to crawl through several files to find what they need. We'd have to keep it up to date, but I think our core library is stabilizing these days.

Does this sound like a good idea? Especially keen to hear from those who have been introduced to working with the DSL more recently: @atondwal @cipher1024 @smore-lore

**Comment by satnam6502** [comment]
YES!
