### ISSUE TITLE
Improve specification for Coq source files

### ISSUE THREAD

**Issue by satnam6502** [project-oak/silveroak#686]
Why does the build system want to use the emacs backup file?

```
/Library/Developer/CommandLineTools/usr/bin/make -C cava
make[1]: *** No rule to make target `Cava/Core/.#Netlist.v', needed by `_CoqProject'.  Stop.
make: *** [cava] Error 2
```

**Comment by atondwal** [comment]
Is this on glinux? I can't reproduce. Seems that the meaning of `*` in findutils _depends on your version_ of findutils. Anyways, here's a patch that should fix the issue.

**Comment by satnam6502** [comment]
On Mac OS X.
