### ISSUE TITLE
Update to Coq 8.13

### ISSUE THREAD

**Issue by jadephilipoom** [project-oak/silveroak#730]
[Coq 8.13 is out](https://coq.inria.fr/news/coq-8-13-0-is-out.html) (as of January). We should make sure we're compatible by updating the CI to either check both 8.13 and 8.12, or just 8.13. If the latter, we should update our own local installations as well.

I'd personally lean towards checking just one version at this stage of the project; although it's nice to support multiple, it can slow down PRs and it's annoying to debug a version of Coq you don't have.

**Comment by blaxill** [comment]
As stated in #729 upgrading bedrock2 will require moving to Coq 8.13
