### ISSUE TITLE
Revert to using tuples for the circuit port interface specification

### ISSUE THREAD

**Issue by satnam6502** [project-oak/silveroak#754]
Earlier we used tuples to represent the input signals and output signals for circuit interfaces, but then we switched to using a list (for a reason I can't recall, my fault). So instead of writing:

```coq
Definition fullAdderInterface
  := combinationalInterface "fullAdder"
     [mkPort "cin" Bit; mkPort "a" Bit; mkPort "b" Bit]
     [mkPort "sum" Bit; mkPort "carry" Bit].
```

we could go back to:

```coq
Definition fullAdderInterface
  := combinationalInterface "fullAdder"
     (mkPort "cin" Bit, mkPort "a" Bit, mkPort "b" Bit)
     (mkPort "sum" Bit, mkPort "carry" Bit).
```

**Comment by jadephilipoom** [comment]
Seems like this is no longer applicable now that we're moving to cava2; closing the issue.
