### ISSUE TITLE
Mock mmio write/read functions so OT's unit tests run

### ISSUE THREAD

**Issue by jadephilipoom** [project-oak/silveroak#816]
> Also, unittest will not run because we don't have mock functions for `b2_abs_mmio_write32` and `b2_abs_mmio_read32`.

Maybe we could write them; I'll make an issue to look into this.

_Originally posted by @jadephilipoom in https://github.com/project-oak/silveroak/issues/815#issuecomment-855738626_

**Comment by satnam6502** [comment]
@jadephilipoom can this be closed via #831 ?

**Comment by jadephilipoom** [comment]
Yep, looks like it!
